const ELECTRICAL_EQUIPMENTS = {
  LIGHT: 'light',
  AC: 'AC'
}

const ELECTRICAL_EQUIPMENTS_POWER = {
	LIGHT: 5,
	AC: 10
};

module.exports = {
  ELECTRICAL_EQUIPMENTS,
  ELECTRICAL_EQUIPMENTS_POWER
}